const AccountController = require('@controller/client/account/account.js');
const withPagination = require('@middleware/withPagination.js');
const withAdminUser = require('@middleware/withAdminUser.js');
const withFullUser = require('@middleware/withFullUser.js');
const withClerk= require('@middleware/withClerk.js');
const withManager= require('@middleware/withManager.js');
module.exports = function (router) {
    router.get('/customer',[withFullUser,withPagination],AccountController.getCustomers);
    router.post('/customer',[withClerk],AccountController.createCustomer);
    router.put('/customer/:id',[withClerk],AccountController.updateCustomer);
    router.delete('/customer/:id',[withManager],AccountController.deleteCustomer);
    router.get('/property',[withFullUser,withPagination],AccountController.getProperties);
    router.post('/property',[withClerk],AccountController.createProperty);
    router.delete('/property/:id',[withManager],AccountController.deleteProperty);
    router.put('/property/:id',[withClerk],AccountController.updateProperty);
    router.post('/manager',[withAdminUser],AccountController.createManager);
    router.delete('/manager/:id',[withAdminUser],AccountController.deleteManager);
    router.post('/clerk',[withManager],AccountController.createClerk);
    router.delete('/clerk/:id',[withManager],AccountController.deleteClerk);
    router.post('/settings',[withAdminUser],AccountController.createSettings);
    router.put('/settings/:id',[withAdminUser],AccountController.updateSettings);
    router.get('/settings',[withAdminUser,withPagination],AccountController.getSettings);
    router.delete('/settings/:id',[withAdminUser],AccountController.deleteSettings);
    router.post('/report',[withClerk],AccountController.createReport);
    router.put('/report/:id',[withClerk],AccountController.updateReport);
    router.get('/report',[withFullUser,withPagination],AccountController.getReports);
    router.delete('/report/:id',[withManager],AccountController.deleteReport);
    router.post('/tenancy',[withClerk],AccountController.createTenancy);
    router.put('/tenancy/:id',[withClerk],AccountController.updateTenancy);
    router.get('/tenancy',[withFullUser,withPagination],AccountController.getTenancies);
    router.delete('/tenancy/:id',[withManager],AccountController.deleteTenancy);
    router.post('/report_response',[withClerk],AccountController.createReportResponse);
    router.put('/report_response/:id',[withClerk],AccountController.updateReportResponse);
    router.get('/report_response',[withFullUser,withPagination],AccountController.getReportResponses);
    router.delete('/report_response/:id',[withManager],AccountController.deleteReportResponse);
    router.post('/report/start_inspection/:id',[withClerk],AccountController.startReportInspection);
    router.get('/dashboard/stats',[withFullUser],AccountController.getDashboardStats);
    router.get('/users',[withFullUser,withPagination],AccountController.getUsers);
}